`torch.Tensor` 是存储和变换数据的主要工具。

`Tensor` 与 NumPy 的多维数组非常类似，但 `Tensor` 提供GPU计算和自动求梯度等更多功能，更加适合深度学习。

`Tensor` 即为”张量“，可以看做为一个多维数据。

> 标量可以看作是0维张量，向量可以看作1维张量，矩阵可以看作二维张量。

### 2.2.1 创建`Tensor`

In [2]:
import torch
# 创建未初始化的tensor
x = torch.empty(5, 3)
print(x)

tensor([[4.2351e+12, 3.0945e-41, 0.0000e+00],
        [0.0000e+00, 4.2344e+12, 3.0945e-41],
        [4.2344e+12, 3.0945e-41, 4.2344e+12],
        [3.0945e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [12]:
# 创建随机初始化的tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.6387, 0.3633, 0.6102],
        [0.3081, 0.9135, 0.9624],
        [0.2534, 0.1341, 0.5390],
        [0.4373, 0.5965, 0.9568],
        [0.0874, 0.0692, 0.2635]])


In [8]:
# 创建long型全0的tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# 直接根据数据创建tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
# 通过现有的tensor创建，会默认重用输入tensor的属性，如数据类型
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1496,  0.1086,  1.3319],
        [ 1.5724, -1.4965,  0.4204],
        [-0.3620,  1.0855,  0.2206],
        [ 0.3139,  1.3442,  3.0412],
        [-0.4156,  0.6823, -0.2777]])


In [16]:
# 获取tensor的形状，torch.Size其实是个tuple，支持所有tuple操作
print(x.size())
print(type(x.size()))
print(x.shape)
print(type(x.shape))

torch.Size([5, 3])
<class 'torch.Size'>
torch.Size([5, 3])
<class 'torch.Size'>


### 2.2.2 操作

#### 算术操作

In [21]:
# 加法
# 形式一
y = torch.rand(5, 3)
print(x + y)

# 形式二
print(torch.add(x, y))
# 还可以指定输出对象
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# 形式三
# PyTorch操作inplace版本都有后缀 _，例如 x.copy_(y)、x.t_()
y.add_(x)
print(y)

tensor([[ 0.6848,  0.5394,  2.2371],
        [ 1.6719, -0.6280,  0.4771],
        [ 0.4528,  1.4676,  0.9897],
        [ 0.6461,  1.4832,  3.2895],
        [ 0.0416,  1.3725, -0.1802]])
tensor([[ 0.6848,  0.5394,  2.2371],
        [ 1.6719, -0.6280,  0.4771],
        [ 0.4528,  1.4676,  0.9897],
        [ 0.6461,  1.4832,  3.2895],
        [ 0.0416,  1.3725, -0.1802]])
tensor([[ 0.6848,  0.5394,  2.2371],
        [ 1.6719, -0.6280,  0.4771],
        [ 0.4528,  1.4676,  0.9897],
        [ 0.6461,  1.4832,  3.2895],
        [ 0.0416,  1.3725, -0.1802]])
tensor([[ 0.6848,  0.5394,  2.2371],
        [ 1.6719, -0.6280,  0.4771],
        [ 0.4528,  1.4676,  0.9897],
        [ 0.6461,  1.4832,  3.2895],
        [ 0.0416,  1.3725, -0.1802]])


#### 索引

通过索引操作来访问 tensor 的一部分。

**索引出来的结果与原数据共享内存，即一个修改，另一个会跟着修改**

In [28]:
print(x)
y = x[0, :]  # 第0行的所有列
y += 1
print(y)
print(x)

tensor([[ 0.1496,  0.1086,  1.3319],
        [ 1.5724, -1.4965,  0.4204],
        [-0.3620,  1.0855,  0.2206],
        [ 0.3139,  1.3442,  3.0412],
        [-0.4156,  0.6823, -0.2777]])
tensor([1.1496, 1.1086, 2.3319])
tensor([[ 1.1496,  1.1086,  2.3319],
        [ 1.5724, -1.4965,  0.4204],
        [-0.3620,  1.0855,  0.2206],
        [ 0.3139,  1.3442,  3.0412],
        [-0.4156,  0.6823, -0.2777]])


In [34]:
# index_select（输入，维度，行/列索引）
print(torch.index_select(x, 0, torch.tensor([0, 2])))
print(torch.index_select(x, 1, torch.tensor([1, 2])))

tensor([[ 1.1496,  1.1086,  2.3319],
        [-0.3620,  1.0855,  0.2206]])
tensor([[ 1.1086,  2.3319],
        [-1.4965,  0.4204],
        [ 1.0855,  0.2206],
        [ 1.3442,  3.0412],
        [ 0.6823, -0.2777]])


#### 改变形状

view() 返回的新 tensor 与源 tensor 虽然可能有不同的 size，但是共享 data！即修改一个，另一个也跟着改变。

In [37]:
# 用view()改变形状
y = x.view(15)
z = x.view(-1, 5) # -1所指的维度可以根据其他维度的值推出来
print(x)
print(y)
print(z)

tensor([[ 1.1496,  1.1086,  2.3319],
        [ 1.5724, -1.4965,  0.4204],
        [-0.3620,  1.0855,  0.2206],
        [ 0.3139,  1.3442,  3.0412],
        [-0.4156,  0.6823, -0.2777]])
tensor([ 1.1496,  1.1086,  2.3319,  1.5724, -1.4965,  0.4204, -0.3620,  1.0855,
         0.2206,  0.3139,  1.3442,  3.0412, -0.4156,  0.6823, -0.2777])
tensor([[ 1.1496,  1.1086,  2.3319,  1.5724, -1.4965],
        [ 0.4204, -0.3620,  1.0855,  0.2206,  0.3139],
        [ 1.3442,  3.0412, -0.4156,  0.6823, -0.2777]])


In [41]:
# 数据共享
y += 1
print(y)
print(x)

tensor([ 1.1496,  1.1086,  2.3319,  1.5724, -1.4965,  0.4204, -0.3620,  1.0855,
         0.2206,  0.3139,  1.3442,  3.0412, -0.4156,  0.6823, -0.2777])
tensor([[ 1.1496,  1.1086,  2.3319],
        [ 1.5724, -1.4965,  0.4204],
        [-0.3620,  1.0855,  0.2206],
        [ 0.3139,  1.3442,  3.0412],
        [-0.4156,  0.6823, -0.2777]])


如果不想共享数据，可以利用 `replace()` 改变形状，但此函数并不能保证返回的是其拷贝，所以不推荐使用！

推荐使用：先用 `clone()` 创造一个副本，然后再使用 `view`。

使用 `clone` 还有一个好处，会被记录在计算图中，即梯度回传到副本时也会传到源 `Tensor`

In [42]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.1496,  0.1086,  1.3319],
        [ 0.5724, -2.4965, -0.5796],
        [-1.3620,  0.0855, -0.7794],
        [-0.6861,  0.3442,  2.0412],
        [-1.4156, -0.3177, -1.2777]])
tensor([ 1.1496,  1.1086,  2.3319,  1.5724, -1.4965,  0.4204, -0.3620,  1.0855,
         0.2206,  0.3139,  1.3442,  3.0412, -0.4156,  0.6823, -0.2777])


`item()`：可以将标量`Tensor`转换成一个Python number

In [45]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8719])
0.8719181418418884


#### 线性代数

支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等，避免重复造轮子。

### 2.2.3 广播机制

对于两个形状不同的 tensor 按元素运算时，可能会触发广播机制。

广播机制：先适当复制元素使这两个 `Tensor` 形状相同后再按元素运算。

In [48]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)
print(x)
print(y)
print(x + y)
# x中的第一行的两个元素被广播（复制）到第二和第三行
# y中第一列的三个元素被广播（复制）到了第二列
# 从而可以对两个3行2列的矩阵按元素相加了

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.2.4 运算的内存开销

索引操作不会开辟新内存；但 `y = x + y`这样的运算会新开内存，然后将 y 指向新内存。

`id`函数：如果两个实例的ID一致，那么它们所对应的内存地址相同，反之则不同。

In [49]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [51]:
# 如果想指定结果到原来 y 的内存，使用索引来进行替换操作
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [52]:
# 使用全名函数中的 out 参数或者自加运算符也可
torch.add(x, y, out=y)
y.add_(x)
print(y)

tensor([ 7, 12])


### 2.2.5 Tensor和NumPy相互转换

可以用 `numpy()` 和 `from_numpy()` 将 Tensor 和 NumPy中的数组相互转换。

**注意**：这两个函数所产生的 Tensor 和 NumPy中的数组共享相同的内存，改变其中一个另一个也会改变。

> 将Numpy中的array转换成 Tensor 的方法就是 `torch.tensor()`，词方法总是会进行数据拷贝（消耗更多的时间合空间），返回的 `Tensor` 和原来的数据不再共享内存。

##### Tensor 转 NumPy

In [55]:
a = torch.ones(5)
b = a.numpy()
print(a, type(a))
print(b, type(b))
a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


#### NumPy数组 转 Tensor

In [57]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### tensor() 不再数据共享

In [59]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### 2.2.6 Tensor on GPU

`to()` 方法将 Tensor 在 CPU和GPU之间相互移动。

In [60]:
x

tensor([1, 2])

In [61]:
if torch.cuda.is_available():
    device = torch.device("cuda") # GPU
    y = torch.ones_like(x, device=device)  # 在GPU上创建一个Tensor
    x = x.to(device)  # 等价于.to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))  # to()还可以同时更改数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
