In [1]:
import numpy as np

In [2]:
np.random.randn(50)

array([ 0.29408313,  1.94292474,  1.35217016, -3.4699071 , -1.41086882,
       -1.77910566,  1.51874139, -1.29212105, -0.08188622,  0.34941927,
       -0.32803657,  1.47535608, -1.24003455, -0.49094648,  0.87774575,
       -0.10434   ,  0.57767602, -1.07825793, -0.09505904,  0.37240485,
        0.79524819,  0.97283289,  0.42221334,  1.17747485, -1.19418629,
        0.55622866, -1.66996497, -0.99587527,  0.43528703,  2.3246665 ,
        0.53841634,  1.13246296, -0.60349932, -0.47470092, -0.92665066,
       -1.098604  , -1.52637534, -0.32692781,  0.91529806,  0.53305522,
       -0.25386389, -0.65991138,  1.32826717,  0.52939558,  1.8756378 ,
        0.81222071,  0.68779948, -0.84244518, -0.48527462,  0.74440896])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10).cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [6]:
a = {'a': 1, 'b': 2, 'c': 3}
print(**a)

TypeError: 'a' is an invalid keyword argument for print()